In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [7]:
dependent = dataset[['charges']]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {
    'criterion':['squared_error', 'absolute_error', 'poisson'],
    'max_features':['log2','sqrt'],
    'splitter':['random','best']
}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1 )
grid.fit(independent, dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['log2', 'sqrt'],
                         'splitter': ['random', 'best']},
             verbose=3)

In [9]:
print(grid.best_estimator_)

DecisionTreeRegressor(criterion='absolute_error', max_features='sqrt',
                      splitter='random')

In [11]:
table = pd.DataFrame.from_dict(grid.cv_results_)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.122053,0.019566,0.009705,0.002457,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.631003,0.590813,0.705447,0.696166,0.676467,0.659979,0.043063,8
1,0.098169,0.082402,0.011912,0.007681,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.746264,0.552653,0.660724,0.657049,0.673791,0.658096,0.061881,9
2,0.016526,0.003424,0.010223,0.003286,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.693888,0.536216,0.682838,0.543605,0.574260,0.606161,0.068408,12
3,0.018694,0.002376,0.008143,0.000751,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.761846,0.534631,0.585222,0.710867,0.737425,0.665998,0.089536,5
4,0.033911,0.005097,0.009576,0.001663,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.719957,0.477374,0.595816,0.713020,0.580908,0.617415,0.090626,11
5,0.033398,0.006238,0.007619,0.000648,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.675491,0.593179,0.713040,0.724096,0.690866,0.679334,0.046282,3
6,0.027211,0.002234,0.007119,0.001179,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.731347,0.693935,0.790979,0.623908,0.682102,0.704454,0.055331,1
7,0.032185,0.007766,0.007907,0.002189,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.688635,0.561227,0.700310,0.711702,0.643060,0.660987,0.055057,7
8,0.013996,0.002028,0.008990,0.001885,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.696138,0.600073,0.600541,0.643231,0.564680,0.620933,0.045096,10
9,0.015776,0.002407,0.006432,0.000708,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.696916,0.610423,0.537038,0.717599,0.768779,0.666151,0.082343,4
10,0.012511,0.000253,0.007627,0.001255,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.713059,0.668349,0.702554,0.684325,0.633877,0.680433,0.027866,2
11,0.015845,0.003046,0.007580,0.001500,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.747748,0.568967,0.636291,0.672859,0.699000,0.664973,0.060186,6

In [13]:
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("Children:"))
sex_male_input = int(input("Sex Male 0 or 1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1:"))

In [16]:
grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])

c:\Hope\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([3594.17085])